#!/bin/sh

# Create a proxy for gfal, because it segfaults with the normal certs
grid-proxy-init -cert /etc/grid-security/gracc.opensciencegrid.org-cert.pem -key /etc/grid-security/gracc.opensciencegrid.org-key.pem -out /etc/grid-security/gracc.opensciencegrid.org-proxy.pem


# Run the actual command
backup_report -c /test.toml djw8605@gmail.com

